# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 14:44
from __future__ import unicode_literals

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summer_field',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
