# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
    ]
